global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['app1:5000', 'app2:5000', 'app3:5000']
    metrics_path: /metrics
